title: Learners Guild
email: info@learnersguild.org
description: > # this means to ignore newlines until "baseurl:"
  Give us 40 weeks to challenge, guide, and support you in the most engaging learning experience you’ve ever had.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.learnersguild.org

# contact details
contact_email: info@learnersguild.org
twitter_username: LearnersGuildUS
facebook_username: LearnersGuild
github_username: LearnersGuild

# Build settings
markdown: kramdown

exclude: [.gitignore, .sass-cache, CNAME, Gemfile, Gemfile.lock, README.md]
