(function(g){var window=this;var d8=function(a,b){return g.aa[a]=b},Rsa=function(a,b){var c=new g.zp;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},e8=function(a){return a.g?a.g.languageCode:a.o},f8=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.Ap(a),kind:a.B,name:a.C,id:a.xa,is_servable:a.O,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},g8=function(a,b,c,d,e){g.Qm.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},h8=function(a,b,c,d,e,f,k){g.Qm.call(this,a,a+b,{priority:c,
namespace:"captions"});this.windowId=d;this.text=e;this.C=f||!1;this.o=k||null},Ssa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.fq=!0;break;case "u":k.ar=!0;break;case "font":var m=f.getAttribute("color");i8.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new h8(a,b,c,d,n.nodeValue,e||0<m,g.Vb(k)?void 0:k));else{var q={};g.za(q,k);Ssa(a,b,c,d,e||0<m,n,q,l)}}},j8=function(a){var b="_"+Tsa++;
return new g8(0,0x8000000000000,0,b,a||{})},Usa=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Tv("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Ssa(d,e,k,b,f,a.firstChild,{},c)},k8=function(){},Vsa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},l8=function(){this.ya=[]},m8=function(){this.g=null},Wsa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.fq=!0;break;case "u":l.ar=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new h8(b,c,d,e.id,q.nodeValue,f||0<n,g.Vb(l)?void 0:l),m.push(q),e!=a.g&&e.o.push(q);else{var t={};g.za(t,l);Wsa(a,b,c,d,e,!0,q,t,m)}}},n8=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},Xsa=function(){this.A=[];
this.g=[];this.o=-1},o8=function(a,b){return b?a.g.concat(a.A):a.g},p8=function(a,b){switch(b.B){case "asr":Ysa(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;Ysa(b,a.g)}},Ysa=function(a,b){g.ab(b,(0,g.A)(a.J,a))||b.push(a)},Zsa=function(a,b){var c=g.$a(a.g,(0,g.A)(b.J,b));
-1!=c&&(a.o=c)},q8=function(a){this.g={};
this.C={};this.D={};this.A="_"+Tsa++;this.B=a},r8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},s8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},t8=function(a,b){var c=r8(a,b);
if(void 0!=c)return c},u8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return i8.test(c),c},$sa=function(a,b){var c={},d=b.getAttribute("ws");
g.za(c,d?a.D[d]:a.B);d=t8(b,"mh");null!=d&&(c.mq=d);d=t8(b,"ju");null!=d&&(c.textAlign=d);d=t8(b,"pd");null!=d&&(c.Vi=d);d=u8(b,"wfc");null!=d&&(c.windowColor=d);d=r8(b,"wfo");void 0!=d&&(c.bj=d/255);return c},ata=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.za(c,a.C[d]);d=t8(b,"ap");null!=d&&(c.eh=d);d=r8(b,"cc");null!=d&&(c.Zt=d);d=r8(b,"ah");null!=d&&(c.Ai=d);d=r8(b,"rc");null!=d&&(c.Wm=d);d=r8(b,"av");null!=d&&(c.Yi=d);return c},bta=function(a,b,c){var d={};
g.za(d,ata(a,b));g.za(d,$sa(a,b));c?(c=a.A,Vsa(d,a.B)&&(d=a.B)):c=b.getAttribute("id")||"0";a=r8(b,"t");b=r8(b,"d")||0x8000000000000;return new g8(a,b,0,c,d)},v8=function(){this.A={};
this.g=null},w8=function(a){this.A=a;
this.g=null},x8=function(a){if(!cta.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(dta,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},y8=function(a,b,c,d){g.K.call(this);
this.H=b;this.C=new l8;this.g=null;this.G=d;this.o=this.A=null;this.L=c;this.D=new g.Od(this.F,1E3,this);g.L(this,this.D);b.addEventListener("seekto",this.B,this);this.B(b.getCurrentTime());this.F()},z8=function(a){this.Rv=!!a;
this.g=new Xsa;this.D=[];this.A=null},fta=function(a){var b={};
if(a=e8(a))b.lang=a,eta.test(a)&&(b.Vi=1);return b},gta=function(a,b){return g.ab(o8(a.g,!0),function(a){return a.toString()==b})},A8=function(a,b,c,d,e,f){this.C=[];
this.H=!1;this.A=a;this.F=[];this.G=[];this.Ha=e;this.Ba=f;this.D=null;this.P=.96*e;this.la=.96*f;this.o={};g.za(this.o,b);g.za(this.o,this.A.params);g.za(this.o,c);e={};g.za(e,b.ab);this.A.params.ab&&g.za(e,this.A.params.ab);g.za(e,c.ab);this.o.ab=e;this.pa=c;g.W.call(this,{K:"div",$:"caption-window",aa:{id:"caption-window-"+a.id,dir:1==this.o.Vi?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:this.o.lang},T:[{K:"span",$:"captions-text"}]});this.B=this.ra["captions-text"];this.ga=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=0;this.ba=this.J*hta(e);a=new g.nl(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.aQ,this);a.subscribe("dragmove",this.$P,this);a.subscribe("dragend",this.ZP,this);this.da=this.ca=0;a="";this.o.bj&&(a=x8(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.bj+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":ita[this.o.textAlign]};this.ga&&(b["border-radius"]=a?this.ba/
8+"px":"");g.ck(this.element,b);switch(this.o.eh){case 0:case 1:case 2:g.O(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.O(this.element,"ytp-caption-window-bottom")}},hta=function(a){var b=1+.25*(a.Zh||0);
if(0==a.offset||2==a.offset)b*=.8;return b},B8=function(a,b){var c={};
if(null!=b.xe||b.background){var d=null!=b.xe?b.xe:a.o.ab.xe,e=x8(b.background?b.background:a.o.ab.background);c.background="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ba/8+"px")}if(null!=b.Zh||null!=b.offset)c["font-size"]=a.J*hta(b)+"px";e=1;if(b.color||null!=b.Rg)d=x8(b.color||a.o.ab.color),e=null==b.Rg?a.o.ab.Rg:b.Rg,d="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")",c.color=d,c.fill=d;if(null!=b.Lf&&0!=b.Lf){var d="rgba(34, 34, 34, "+e+")",f=
"rgba(204, 204, 204, "+e+")";b.Pt&&(f=d=b.Pt);var k=a.J/16/2,l=Math.max(k,1),m=Math.max(2*k,1),e=Math.max(3*k,1),n=Math.max(5*k,1),q=[];switch(b.Lf){case 4:for(l=e;l<=n;l+=k)q.push(m+"px "+m+"px "+l+"px "+d);break;case 1:for(k=2<=window.devicePixelRatio?.5:1;l<=e;l+=k)q.push(l+"px "+l+"px "+d);break;case 2:q.push(l+"px "+l+"px "+f);q.push(-l+"px "+-l+"px "+d);break;case 3:for(l=0;5>l;l++)q.push("0 0 "+m+"px "+d)}c["text-shadow"]=q.join(", ")}d="";switch(b.fontFamily){case 1:d='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:d='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:d='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:d='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:d='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:d=g.xi()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:d=
'Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}d&&(c["font-family"]=d);d=b.offset;null==d&&(d=a.o.ab.offset);switch(d){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.fq&&(c["font-style"]="italic");b.ar&&(c["text-decoration"]="underline");b.zp&&(c.visibility="hidden");return c},jta=function(a,b,c){a.H=a.H||!!c;
var d={};g.za(d,a.o.ab);g.za(d,c||b.o);g.za(d,a.pa.ab);var e=a.F[0],f;if(e&&d.background==e.background&&d.xe==e.xe&&!!d.zp==!!e.zp&&d.Lf==e.Lf){for(c=0;c<a.F.length;c++)if(Vsa(d,a.F[c])){f=a.G[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.Se("SPAN");g.ck(f,B8(a,c));a.G[0].appendChild(f);c=1}a.G.length=c;a.F.length=c}else a.G.length=0,a.F.length=0,f=g.Se("SPAN"),g.ck(f,B8(a,d)),a.B.appendChild(f);a.D&&a.D.parentNode!=f&&(g.Ze(a.D),f.appendChild(a.D));e=(k=g.z(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.C.length||!b.C){if(0<c||0!=a.C.length){var m=g.Se("BR");f.appendChild(m)}f.appendChild(g.Te("\u00a0"));a.D=g.Te("\u00a0");f.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.Te(l):l,m))}a.F.push(d);a.G.push(f);a.C.push(b)},C8=function(a,b,c,d){z8.call(this,d);
c=c||g.Qh(a).hl||"";c=c.split("_").join("-");this.B=g.Sh(a,{hl:c});this.C=b;this.F={};this.o=null},D8=function(a,b,c,d,e,f){A8.call(this,a,b,c,d,e,f);
g.O(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.X=0;this.N=window.NaN;this.ka=null;this.ea=new g.Od(this.va,433,this);g.L(this,this.ea)},E8=function(a){if(!a.L){var b=g.Se("SPAN");
g.ck(b,B8(a,a.o.ab));a.B.appendChild(b);b.appendChild(g.Te("M"));var c=b.offsetHeight,d=g.Se("BR");b.appendChild(d);b.appendChild(g.Te("M"));a.L=b.offsetHeight-c;a.B.removeChild(b)}return a.L},F8=function(a,b,c,d,e,f){A8.call(this,a,b,c,d,e,f);
this.type=1},G8=function(a,b){z8.call(this);
this.B=a;this.Z=b;this.o=null},H8=function(a){z8.call(this,a.ql);
this.o=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},kta=function(a){for(var b in a)delete a[b]},L8=function(a){g.qu.call(this,a);
g.fz();this.Y=g.V(a);this.B=a.getVideoData();this.ea=g.sm(a);this.Z=a;var b=null,c=g.Yh("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zh(c));this.X=b;this.C={ab:{}};this.D={ab:{}};this.J=[];this.H={};this.N={};this.O=!1;this.ka="1"==this.B.Qb.cc_auto_caps||"1"==this.Y.O.cc_auto_caps;c=b=this.A=this.o=this.G=this.F=this.L=this.da=null;I8(this)||(b=new g.Od(this.hz,0,this),g.L(this,b),c=new g.Od(this.RM,2E3,this),g.L(this,c));this.ba=b;this.ga=c;this.P=new g.fo(this);g.L(this,this.P);
I8(this)||this.P.W(a,"resize",this.fr);this.P.W(a,"onPlaybackAudioChange",this.FI);this.P.W(a,"crn_captions",this.JP,this);this.P.W(a,"crx_captions",this.KP,this);J8(this,K8(this,"display-settings")||{});lta(this)&&this.load()},I8=function(a){return"3"!=a.Y.B?!1:!!a.Z.app.F.fn()},mta=function(a){var b;
a.B.captionTracks.length&&(b=a.g.Hh().Jt);if(3==b||1==a.Y.og||1==a.B.og||"alwayson"==a.B.bf("yt:cc"))return!0;if(2==a.Y.og){var c=K8(a,"module-enabled");if(null!=c)return!!c}return 2==b||"on"==a.B.bf("yt:cc")},lta=function(a){return I8(a)?!a.B.Ca:a.B.captionTracks.length&&a.g.Hh().xj?!0:mta(a)},ota=function(a,b){if(!g.V(a.g).experiments.g("legacy_default_captions")){if(a.o){var c=o8(a.o.g,b||a.ka),d=K8(a,"recent-langs");
if(d){for(var e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d[e]==e8(c[f]))return c[f];for(e=0;e<d.length;e++)for(var k=d[e].match(nta)[0],f=0;f<c.length;f++){var l=e8(c[f]).match(nta)[0];if(k==l)return c[f]}}return a.G&&a.G.Vh?a.G.Vh:c[0]||M8(a)}return null}c=null;a.o&&(c=a.o.Hu(),!c&&b&&(c=o8(a.o.g,!0)[0]),c||!b&&!a.ka||(d=a.o.g.A,d.length&&(c=gta(a.o,d[0].toString()))),c||(c=M8(a)));return c},M8=function(a){return g.V(a.g).experiments.g("legacy_default_captions")?a.o.Ju():a.G&&a.G.xj},N8=function(a,
b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.A=b;a.load(d)},J8=function(a,b,c){var d=O8.ab;
a.C={};g.za(a.C,O8);a.C.ab={};g.za(a.C.ab,d);a.D={ab:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;i8.test(f);e.ab.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;i8.test(f);e.ab.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||O8.windowColor;i8.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.xe);e.ab.xe=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Zh);e.ab.Zh=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.Rg);e.ab.Rg=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=O8.bj);e.bj=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.Lf);e.ab.Lf=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ab.fontFamily=f;a.loaded&&a.fr();c&&P8(a,"display-settings",b)},qta=function(a,b){if(b&&!a.F){var c=j8({Vi:0,
lang:"en"});a.F=[c,new h8(c.start,c.end-c.start,0,c.id,g.Q("YTP_SAMPLE_SUBTITLES"))];g.Em(a.g,a.F)}else!b&&a.F&&(pta(a,a.F),a.F=null)},pta=function(a,b){g.Gm(a.g,b);
(0,g.I)(b,function(a){g.lb(this.J,a)},a);
a.ba.ke()},rta=function(a,b){return a&&g.z(a)&&i8.test(a)?a:b},sta=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},uta=function(a,b){if(a&&g.z(a)){var c=tta.indexOf(a);
return-1!=c?c:b}return b},wta=function(a,b){if(a&&g.z(a)){var c=vta.indexOf(a);
return-1!=c?c:b}return b},xta=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.re(a,-2,4):b},K8=function(a,b){if(!a.X)return null;
var c;try{c=a.X.get(b)}catch(d){a.X.remove(b)}return c},P8=function(a,b,c){if(a.X)try{a.X.set(b,c)}catch(d){}};
g.zp.prototype.J=d8(4,function(a){return a?this.toString()==a.toString():!1});
g.bo.prototype.fn=d8(3,function(){return!!this.g.textTracks});
g.LZ.prototype.fn=d8(2,function(){return!1});
g.bo.prototype.il=d8(1,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.LZ.prototype.il=d8(0,function(){});
var Tsa=0;g.C(g8,g.Qm);g.C(h8,g.Qm);var i8=/^#(?:[0-9a-f]{3}){1,2}$/i,cta=/^#(?:[0-9a-f]{3}){1,2}$/i,dta=/#(.)(.)(.)/,yta=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,zta=/(?:\r\n|\r|\n){2,}/,Ata=/^NOTE/,Bta=0,eta=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;l8.prototype.contains=function(a){a=g.wb(this.ya,a);return 0<=a||0>a&&1==(-a-1)%2};
l8.prototype.length=function(){return this.ya.length/2};
g.C(m8,k8);
m8.prototype.o=function(a,b){for(var c=[],d=a.split(zta),e=1;e<d.length;e++){var f=d[e],k=b,l=c;if(""!=f&&!Ata.test(f)){var m=g.W3.exec(f);if(m&&3<=m.length){var n=n8(m[1]),m=n8(m[2])-n,f=f.substring(g.W3.lastIndex);g.W3.lastIndex=0;var k=n+k,n=m,q=f,m={};this.g||(this.g=j8({mq:0}),l.push(this.g));var t=this.g,f=5;if(0>q.indexOf("<"))l.push(new h8(k,n,f,t.id,q,!1,g.Vb(m)?void 0:m));else{q=q.split(yta);1!=q.length&&(f=6,t="_"+Bta++,t=new g8(k,n,f,t,{}),l.push(t));for(var v=k,w=0;w<q.length;w++){var B=q[w];
if(0==w%2){var D=g.Tv("<html>"+B+"</html>"),J;D.getElementsByTagName("parsererror").length?(J=D.createElement("span"),J.appendChild(D.createTextNode(B))):J=D.firstChild;Wsa(this,v,n-(v-k),f,t,0<w,J,m,l)}else v=n8(B)}}}g.W3.lastIndex=0}}return c};
g.C(q8,k8);
q8.prototype.o=function(a){a.firstChild.getAttribute("format");var b,c;a=a.firstChild.childNodes;for(var d=0;d<a.length;d++){var e=a[d];switch(e.tagName){case "head":b=e;break;case "body":c=e}}if(b)for(b=b.childNodes,a=0;a<b.length;a++){var f=b[a];switch(f.tagName){case "pen":var e=f.getAttribute("id"),d=this.g,k=f,f={},l=k.getAttribute("p");l&&g.za(f,this.g[l]);l=s8(k,"b");null!=l&&(f.bold=l);l=s8(k,"i");null!=l&&(f.fq=l);l=s8(k,"u");null!=l&&(f.ar=l);l=t8(k,"et");null!=l&&(f.Lf=l);l=t8(k,"of");
null!=l&&(f.offset=l);l=u8(k,"bc");null!=l&&(f.background=l);l=u8(k,"ec");null!=l&&(f.Pt=l);l=u8(k,"fc");null!=l&&(f.color=l);l=t8(k,"fs");void 0!=l&&0!=l&&(f.fontFamily=l);l=r8(k,"sz");void 0!=l&&(f.Zh=l/100-1);l=r8(k,"bo");void 0!=l&&(f.xe=l/255);k=r8(k,"fo");void 0!=k&&(f.Rg=k/255);d[e]=f;break;case "ws":d=f.getAttribute("id");this.D[d]=$sa(this,f);break;case "wp":d=f.getAttribute("id"),this.C[d]=ata(this,f)}}b=[];if(c){a={};c=c.childNodes;for(var d=void 0,m,e=0;e<c.length;e++)switch(f=c[e],f.tagName){case "w":var n=
bta(this,f,!1);(f=a[n.id])&&f.end>n.start&&(f.end=n.start);a[n.id]=n;b.push(n);break;case "p":var q=f,t=d,v=m,k=[],l=q.getAttribute("w")||this.A,w=!!s8(q,"a"),B=r8(q,"t")||0,D=r8(q,"d")||5E3;!v&&!w&&t&&t.windowId==l&&t.end>B&&(t.end=B);for(var t=w?6:5,v=this.g[q.getAttribute("p")],q=q.childNodes,J=0;J<q.length;J++){var H=q[J];0<J&&(w=!0);if("s"==H.tagName)var Aa=H,H=B,ib=D,ga=l,$c=w,Rb=t,Lf=Aa.textContent?Aa.textContent:"",Fi=this.g[Aa.getAttribute("p")],Aa=r8(Aa,"t")||0,H=new h8(H+Aa,ib-Aa,Rb,ga,
Lf,$c,Fi);else H=new h8(B,D,t,l,H.textContent||"",w,v);k.push(H)}d&&"\n"==d.text&&(d.text="");if(0<k.length)for(d=k[k.length-1],m=null!=f.getAttribute("d"),k[0].windowId==this.A&&(n=bta(this,f,!0),b.push(n)),f=0;f<k.length;f++)l=k[f],k[f].windowId=n.id,n.o.push(l),b.push(l)}}return b};
g.C(v8,k8);
v8.prototype.o=function(a){var b=[];this.g||(this.g=j8(),this.A[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=b,e=c.getAttribute("id");a:{var f=c,k=this.A[e];if(f.getAttribute("t")||f.getAttribute("start")){c=f.getAttribute("start")?1E3*(0,window.parseFloat)(f.getAttribute("start")):(0,window.parseInt)(f.getAttribute("t"),10);k&&(k.end>=c?k.end=c:k=null);switch(f.getAttribute("op")){case "kill":c=null;break a;case "define":k=null}k||
(k=j8());var l={};k&&(g.za(l,k.params),k=k.params.ab)&&(l.ab={},g.za(l.ab,k));f.getAttribute("rc")&&(l.Wm=(0,window.parseInt)(f.getAttribute("rc"),10));f.getAttribute("cc")&&(l.Zt=(0,window.parseInt)(f.getAttribute("cc"),10));f.getAttribute("ap")&&(k=(0,window.parseInt)(f.getAttribute("ap"),10),l.eh=0>k||8<k?7:k);f.getAttribute("ah")&&(l.Ai=(0,window.parseInt)(f.getAttribute("ah"),10));f.getAttribute("av")&&(l.Yi=(0,window.parseInt)(f.getAttribute("av"),10));f.getAttribute("vs")&&(l.isVisible=!!f.getAttribute("vs"));
f.getAttribute("ju")&&(l.textAlign=(0,window.parseInt)(f.getAttribute("ju"),10));f.getAttribute("pd")&&(l.Vi=1,0==(0,window.parseInt)(f.getAttribute("pd"),10)&&(l.Vi=0));f.getAttribute("bc")&&(l.ab||(l.ab={}),l.ab.backgroundColor=f.getAttribute("bc"));f.getAttribute("bo")&&(l.ab||(l.ab={}),l.ab.xe=(0,window.parseInt)(f.getAttribute("bo"),10)/100);f.getAttribute("fc")&&(l.ab||(l.ab={}),l.ab.color=f.getAttribute("fc"));f.getAttribute("sd")&&(l.vN=(0,window.parseInt)(f.getAttribute("sd"),10));k=(0,window.parseInt)(f.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(f.getAttribute("dur"))||0x8000000000000;f=f.getAttribute("id")||"0";c=new g8(c,k,0,f,l)}else c=null}this.A[e]=c;d.push(c);break;case "text":for(d=b,e=[],Usa(a,this.g.id,e),c=0;c<e.length;c++)l=e[c],this.A[l.windowId]&&d.push(l)}a=a.nextSibling}return b};
g.C(w8,k8);w8.prototype.o=function(a){var b=[];this.g||(this.g=j8(this.A),b.push(this.g));a=a.firstChild.childNodes;for(var c=0,d=a.length;c<d;c++)Usa(a[c],this.g.id,b);return b};
var ita=["left","right","center"],Cta={zp:!0};g.C(y8,g.K);y8.prototype.R=function(){y8.M.R.call(this);this.H.removeEventListener("seekto",this.B,this);this.o&&this.o.abort()};
y8.prototype.B=function(a){this.g=g.Za(this.L.Ej(a).g)};
y8.prototype.F=function(){this.isDisposed();var a;if(a=null!==this.g)a=this.g,a=a.g.Ek(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.H.getCurrentTime())){a=this.g;a=a.g.Hn(a);if(!this.C.contains(a.g[0].A)){var b=g.Tn(g.Ko(a));this.o=g.Vi(b,{format:"RAW",md:(0,g.A)(this.J,this),withCredentials:!0});this.A=a;var b=this.C,c=this.A.g[0].A,d=g.wb(b.ya,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.ya[d-1]&&d<b.ya.length&&1==b.ya[d]-c?(g.kb(b.ya,d),g.kb(b.ya,d-1)):0<d&&1==c-b.ya[d-1]?b.ya[d-1]=c:
d<b.ya.length&&1==b.ya[d]-c?b.ya[d]=c:(g.sb(b.ya,d,0,c),g.sb(b.ya,d+1,0,c)))}this.g=g.Za(a.g)}this.D.start()};
y8.prototype.J=function(a){this.isDisposed();null==a.responseText||400<=a.status||null===this.G||this.G(a.responseText,1E3*this.A.g[0].startTime);this.o=this.A=null};
g.C(z8,g.K);z8.prototype.Hu=function(a){var b=this.g.o,c=o8(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
z8.prototype.Ju=function(){return null};
z8.prototype.od=function(){this.A=null};
z8.prototype.R=function(){z8.M.R.call(this);this.od()};
g.C(A8,g.W);g.h=A8.prototype;g.h.aQ=function(a,b){var c=g.tk(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.O(this.element,"ytp-dragging")};
g.h.$P=function(a,b){var c=g.wk(this.element),d=a-this.ca-.02*this.Ha,e=b-this.da-.02*this.Ba,f=(d+c.width/2)/this.P*3,f=Math.floor(g.re(f,0,2)),k=(e+c.height/2)/this.la*3,k=Math.floor(g.re(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.P,d=100*g.re(d,0,1),c=(e+k/2*c.height)/this.la,c=100*g.re(c,0,1);this.A.params.eh=l;this.A.params.Yi=c;this.A.params.Ai=d;this.o.eh=l;this.o.Yi=c;this.o.Ai=d;this.Qi(this.C)};
g.h.ZP=function(){g.oh(this.element,"ytp-dragging")};
g.h.Rb=function(){return this.type};
g.h.Qi=function(a){var b=Math.min(this.Ku(),this.P),c=this.Iu();g.ck(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.so(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.o.Ai+2,e=this.o.eh;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Yi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.B.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ck(this.element,a)};
g.h.so=function(a){for(var b=0;b<a.length&&a[b]==this.C[b];b++);if(this.H||this.C.length>b)b=0,this.H=!1,this.C=[],this.F=[],this.G=[],this.D=null,g.We(this.B);for(;b<a.length;b++)jta(this,a[b])};
g.h.Ku=function(){return 0};
g.h.Iu=function(){return 0};
g.h.toString=function(){return A8.M.toString.call(this)};
var nta=/^[^_-]+/;g.C(C8,z8);g.h=C8.prototype;g.h.iq=function(a,b){this.isDisposed();var c=this.Fj(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.od();this.o=g.Vi(c,{format:"RAW",Hb:d,withCredentials:!0});Zsa(this.g,a)};
g.h.jq=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.Rv&&(b.asrs=1);d=g.Sh(d,b);b=(0,g.A)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),q=c,t=e[m].getAttribute("lang_code"),v=e[m].getAttribute("lang_translated"),w=e[m].getAttribute("name"),B=e[m].getAttribute("kind"),D=e[m].getAttribute("id"),J="true"==e[m].getAttribute("lang_default"),
H="true"==e[m].getAttribute("cantran"),Aa=e[m].getAttribute("vss_id");p8(d,new g.zp({formats:n,format:q,languageCode:t,languageName:v,name:w,kind:B,id:D,is_servable:!0,is_default:J,is_translateable:H,vss_id:Aa}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),q=b[e].getAttribute("id"),t="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:q,is_default:t},this.F[l.languageCode]=l.languageName,this.D.push(new g.yp(l))}a()},this);
this.od();this.o=g.Vi(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Fj=function(a){var b=this.B,c={v:this.C,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=e8(a));return b=g.Sh(b,c)};
g.h.od=function(){C8.M.od.call(this);this.o&&this.o.abort()};
g.h.R=function(){this.od();C8.M.R.call(this)};
g.C(D8,A8);D8.prototype.va=function(){g.oh(this.element,"ytp-rollup-mode");this.Qi(this.ka,!0)};
D8.prototype.Ku=function(){var a=this.A.params.Zt;if(!this.X&&a){var b=g.Se("SPAN");g.hf(b,"\u00a0"+(0,g.Na)("\u2014",a)+"\u00a0");g.ck(b,B8(this,this.o.ab));this.B.appendChild(b);this.X=b.offsetWidth;this.B.removeChild(b)}return this.X};
D8.prototype.Iu=function(){return this.A.params.Wm*E8(this)};
D8.prototype.Qi=function(a,b){this.ka=a;if(E8(this)){for(var c=0,d=0;c<this.C.length&&d<a.length;c++)this.C[c]==a[d]&&d++;0<d&&d<a.length&&(a=this.C.concat(a.slice(d)));c=1;for(d=0;d<a.length;d++){var e=a[d];g.z(e.text)&&(c+=e.text.split("\n").length-1,e.C||0==d||c++)}c=this.A.params.Wm-c;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.O(this.element,"ytp-rollup-mode"),this.ea.ke()),d="",c&&(d="translateY("+Math.ceil(c*E8(this))+"px)"),g.ck(this.B,"transform",d),this.N=c);D8.M.Qi.call(this,a)}else D8.M.Qi.call(this,
a)};
g.C(F8,A8);F8.prototype.so=function(a){var b=this.A.o;F8.M.so.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.za(f,e.o),g.za(f,Cta),c=e.o,d=f);jta(this,e,f)}};
g.C(G8,z8);g.h=G8.prototype;g.h.iq=function(a,b){this.od();var c=this.B.g[a.o];c&&(this.o=new y8(0,this.Z,c,function(c,e){b(c,a,e)}))};
g.h.jq=function(a){p8(this.g,new g.zp({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.od=function(){G8.M.od.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.Fj=function(){return""};
g.h.R=function(){this.od();G8.M.R.call(this)};
g.C(H8,z8);g.h=H8.prototype;g.h.iq=function(a,b,c){this.isDisposed();var d=this.Fj(a),e=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.od();this.B=g.Vi(d,{format:"RAW",Hb:e,withCredentials:!0});c&&this.o&&this.o.xj!=a&&(this.o.Vh=a)};
g.h.jq=function(a,b,c,d){this.C=c;if(this.o=d||null)for(b=0;b<this.o.captionTracks.length;b++)p8(this.g,this.o.captionTracks[b]);a()};
g.h.Fj=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.Sh(b,c)};
g.h.Ju=function(){return this.o?this.o.xj:null};
g.h.Hu=function(){return this.o?this.o.Vh:null};
g.h.od=function(){H8.M.od.call(this);this.B&&this.B.abort()};
g.h.R=function(){this.od();H8.M.R.call(this)};
var O8={windowColor:"#080808",bj:0,textAlign:2,eh:7,Ai:50,Yi:100,ab:{background:"#080808",xe:.75,Lf:0,color:"#fff",fontFamily:4,Zh:0,Rg:1,offset:1}},tta=["none","raised","depressed","uniform","dropShadow"],vta="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" ");g.C(L8,g.qu);g.h=L8.prototype;g.h.R=function(){I8(this)||qta(this,!1);L8.M.R.call(this)};
g.h.load=function(a){L8.M.load.call(this);this.G=this.g.Hh();if(this.o||a)this.A?(a?this.Ix(a,this.A):3!=this.g.Va()&&this.o.iq(this.A,(0,g.A)(this.Ix,this),g.V(this.g).experiments.g("legacy_default_captions")),this.g.wa("captionschanged",f8(this.A))):this.g.wa("onCaptionsTrackListChanged");else{var b;this.B.Ca?b=new G8(this.B.sa,this.g):this.B.captionTracks.length?b=new H8(this.B):b=new C8(this.B.rl,this.B.videoId,this.B.Th||this.Y.Th||this.B.bf("yt:cc_default_lang")||this.Y.pa,this.B.ql);this.o=
b;b.jq((0,g.A)(this.ML,this),!0,I8(this)?"vtt":void 0,this.g.Hh())}};
g.h.unload=function(){if(I8(this))for(var a=g.Ge("track",void 0,this.ea.o),b=0;b<a.length;b++)g.Ze(a[b]);else g.Qd(this.ga),g.Hm(this.g,"captions"),this.J=[],this.o&&this.o.od(),this.F&&g.Em(this.g,this.F),this.fr();L8.M.unload.call(this);(a=g.qm(this.g.app))&&g.qV(a);this.g.wa("captionschanged",{})};
g.h.ML=function(){var a;if(this.O||mta(this))a=ota(this,this.O);if(I8(this))for(var b=o8(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.Ap(d),srclang:e8(d),src:this.o.Fj(d)};d==a&&(e["default"]=1);this.Z.app.F.il([g.N("TRACK",e)])}else!this.A&&a&&N8(this,a),this.g.wa("onCaptionsTrackListChanged"),this.g.wa("onApiChange")};
g.h.AN=function(){this.loaded&&!I8(this)&&this.unload()};
g.h.Ix=function(a,b,c){if(a){var d;var e=this.o;try{if(c=c||0,"WEBVTT"==a.substring(0,6))e.A||(e.A=new m8),d=e.A.o(a,c);else{var f=g.Tv(a);f&&f.firstChild?(e.A||("timedtext"==f.firstChild.tagName?3==(0,window.parseInt)(f.firstChild.getAttribute("format"),10)?e.A=new q8(fta(b)):e.A=new v8:e.A=new w8(fta(b))),d=e.A.o(f,c)):d=[]}}catch(k){g.jh(k),d=[]}a={trackName:b.C,trackKind:b.B,trackLangCode:e8(b)};b.g&&(a.fromLangCode=b.o);g.zm(this.g,"cc",a);if(this.A!=M8(this)){!this.O||g.Js(this.Y)||g.Us(this.Y)||
(g.Qd(this.ga),b=j8({eh:0,Ai:5,Yi:5,Wm:2,textAlign:0,Vi:0,lang:"en"}),this.L=[b],a=g.Q("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.da||(e=new g.tu(g.Xg()),g.L(this,e),this.da=e.element),e=b.end-b.start,(f=g.Ap(this.A))&&this.L.push(new h8(b.start,e,0,b.id,f)),this.L.push(new h8(b.start,e,0,b.id,a[0]),new h8(b.start,e,0,b.id,this.da,!0),new h8(b.start,e,0,b.id,a[1],!0)),g.Em(this.g,this.L),this.ga.ke());if(this.O||g.Js(this.Y))P8(this,"module-enabled",!0),g.V(this.g).experiments.g("legacy_default_captions")||
(b=e8(this.A),a=K8(this,"recent-langs"),g.qa(a)||(a=[]),g.lb(a,b),a.unshift(b),3<a.length&&(a.length=3),this.G&&(this.G.Vh=this.A));(b=g.qm(this.g.app))&&g.qV(b)}g.Em(this.g,d);this.O=!1}};
g.h.JP=function(a){this.J.push(a);this.ba.ke()};
g.h.KP=function(a){g.lb(this.J,a);this.ba.ke()};
g.h.EM=function(a){if(a instanceof g8){var b=this.H[a.id];b&&b.A!=a&&(b.dispose(),delete this.H[a.id],b=null);if(!b){var b=this.H,c=a.id;a:{var d=this.ea.Ta(),e=g.pZ(this.ea,!0).height;switch(null!=a.params.mq?a.params.mq:a.params.vN?2:1<a.o.length?1:0){case 1:a=new F8(a,this.C,this.D,e,d.width,d.height);break a;case 2:a=new D8(a,this.C,this.D,e,d.width,d.height);break a;default:a=new A8(a,this.C,this.D,e,d.width,d.height)}}b[c]=a}}else b=a.windowId,this.N[b]||(this.N[b]=[]),this.N[b].push(a)};
g.h.RM=function(){pta(this,this.L);this.L=null};
g.h.hz=function(){this.ba.stop();kta(this.N);this.J.sort(g.Rm);(0,g.I)(this.J,this.EM,this);g.Ib(this.H,function(a,b){!this.N[b]||this.F&&-1==this.F.indexOf(a.A)?(a.dispose(),delete this.H[b]):(a.element.parentNode||g.Km(this.g,a.element,5),a.Qi(this.N[b]))},this)};
g.h.ky=function(){J8(this,{},!0)};
g.h.kp=function(){var a=O8.ab,a={background:a.background,backgroundOpacity:a.xe,charEdgeStyle:a.Lf,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Zh,textOpacity:a.Rg,windowColor:O8.windowColor,windowOpacity:O8.bj},b=K8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.jr=function(a,b){var c={};g.za(c,K8(this,"display-settings"));g.za(c,a);J8(this,c,b);this.g.V("captionssettingschanged")};
g.h.fr=function(){!I8(this)&&this.loaded&&(g.Ib(this.H,function(a,b){a.dispose();delete this.H[b]},this),this.hz())};
g.h.nA=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.re(b,-2,4);this.jr({fontSizeIncrement:c});return c;case "reload":b&&!I8(this)&&N8(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.Y.Eb&&P8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(I8(this))break;if(!g.va(b))break;if(g.Vb(b)){N8(this,null,!0);break}for(var d,e=o8(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
Rsa(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||N8(this,d,!0)}else return this.loaded&&this.A&&this.A!=M8(this)?f8(this.A):{};return"";case "tracklist":return this.o?(0,g.R)(o8(this.o.g,b&&b.includeAsr),function(a){return f8(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.kp();if(g.Js(this.Y)&&b&&g.va(b))if(b.reset)this.ky();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=rta(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=sta(b[c],d[c]);break;case "charEdgeStyle":f[c]=uta(b[c],d[c]);break;case "fontSizeIncrement":f[c]=xta(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=wta(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.jr(f,!0);d=this.kp()}d.fontFamilyOption=vta[d.fontFamily];d.charEdgeStyle=tta[d.charEdgeStyle];return d;case "sampleSubtitles":I8(this)||void 0==b||qta(this,!!b);break;case "xmlTrack":b&&this.Y.Eb&&!I8(this)&&N8(this,new g.zp({languageName:b.name}),!1,b.xml)}};
g.h.HP=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.Y.Eb&&a.push("stickyLoading","xmlTrack");return a};
g.h.IP=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.bz=function(){this.loaded&&this.A?(P8(this,"module-enabled",!1),this.unload()):N8(this,this.A||ota(this,!0),!0)};
g.h.FI=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),lta(this)&&this.load())};
window._exportCheck==g.Ca&&g.u("ytmod.player.captions",L8,void 0);})(_yt_player);
