# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Learner's Guild"
email: dune@learnersguild.org
description: > 
  Learner's Guild is a richly diverse, accelerated learning community. And our 40-week program is a deeply immersive environment for growing savvy developers who know how to collaborate, problem solve, and flurish in both work and life.

# the subpath of your site, e.g. /blog
baseurl: "/github.io"

# the base hostname & protocol for your site
url: "http://learnersguild.github.io" 


twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
